import AbsSat.Cnf.Formula
import AbsSat.Cnf.Dimacs
import AbsSat.Cnf.BruteForce
import AbsSat.Cnf.UnitProp
import AbsSat.Cnf.HornModel
import AbsSat.GraphMap.CnfMap
import AbsSat.GraphMap.CnfMapDiff
import AbsSat.GraphPath.Model.MapReachable
import AbsSat.GraphPath.Model.CnfChain
import AbsSat.GraphPath.Model.L7
import AbsSat.GraphPath.Model.Conservation
import AbsSat.GraphPath.Model.PureDriver
import AbsSat.GraphMap.CnfSel
-- lean_project/AbsSat.lean

import AbsSat.GraphPath.GraphPath
-- import AbsSat.GraphPath.GraphPathFilter -- Logic merged into GraphPath

import AbsSat.GraphPath.GraphPathVisual
import AbsSat.GraphPath.Reader.PathReader
import AbsSat.GraphPath.Reader.PathExpReader
import AbsSat.SatMachine.DiffTest
import AbsSat.Utils.ExhaustiveSolver
import AbsSat.Utils.Checker
import AbsSat.Db.Machine.Cols.ColTimeline
import AbsSat.Db.Map.Cols.MapColVars
import AbsSat.GraphMap.MapReqs
import AbsSat.GraphMap.Hypergraph
import AbsSat.GraphMap.HyperProbe
import AbsSat.Utils.Alias
import AbsSat.Db.Path.Cols.PathColNodes
import AbsSat.Db.Path.Docs.PathDocNode
import AbsSat.Db.Path.Docs.PathDocOwners

-- Pure-model formal verification (soundness + completeness of the
-- abstract 3SAT machine). Imported here so the proofs are checked as
-- part of the default build, not just on demand.
import AbsSat.SatMachine.Model.Soundness
import AbsSat.SatMachine.Model.Completeness
import AbsSat.SatMachine.PureProofs

-- Pure mirror of the Owners graph (bridge phases F1-F2: structures,
-- operations, and the review-loop fuel lemmas). Same rationale.
import AbsSat.GraphPath.Model.GPathM
import AbsSat.GraphPath.Model.Fuel
import AbsSat.GraphPath.Model.Reachable
import AbsSat.GraphPath.Model.Denot
import AbsSat.GraphPath.Model.OwnersInvariants
import AbsSat.GraphPath.Model.Filter
import AbsSat.GraphPath.Model.L6
import AbsSat.GraphPath.Model.Join
import AbsSat.GraphPath.Model.Up
import AbsSat.GraphPath.Model.L6Up
import AbsSat.GraphPath.Model.Review
import AbsSat.GraphPath.Model.CleanInvalid
import AbsSat.GraphPath.Model.Coherence
import AbsSat.GraphPath.Model.AddNode
import AbsSat.GraphPath.Model.JoinSound
import AbsSat.GraphPath.Model.ArcConsistency
import AbsSat.GraphPath.Model.ZeroOneAll
import AbsSat.GraphPath.Model.Link
import AbsSat.GraphPath.Model.WidthProbe
import AbsSat.GraphPath.Model.Validate
import AbsSat.GraphPath.Model.L6Search
import AbsSat.GraphPath.Model.Certificate
import AbsSat.GraphPath.Model.Verdict
import AbsSat.GraphPath.Model.NodeIds
import AbsSat.GraphPath.Model.Reader
import AbsSat.GraphPath.Model.Extendable
import AbsSat.GraphPath.Model.DownVerdict
import AbsSat.GraphPath.Model.PickInduction
import AbsSat.GraphPath.Model.Certifies
import AbsSat.GraphPath.Model.GownersNodes
import AbsSat.GraphPath.Model.Candidates
import AbsSat.GraphPath.Model.Parents
import AbsSat.GraphPath.Model.PathExists
import AbsSat.GraphPath.Model.Ownership
import AbsSat.GraphPath.Model.Sons
import AbsSat.GraphPath.Model.SelfOwn
import AbsSat.GraphPath.Model.MapChain
import AbsSat.GraphPath.Model.ParentId
import AbsSat.GraphPath.Model.Bridge
import AbsSat.GraphPath.Model.Pinned
import AbsSat.GraphPath.Model.Threaded
import AbsSat.GraphPath.Model.Survive
import AbsSat.GraphPath.Model.ExtendSearch
import AbsSat.GraphPath.Model.SymReview
import AbsSat.GraphMap.SymCampaign
import AbsSat.GraphPath.Model.Fabric
import AbsSat.GraphPath.Model.NodeInvariant
import AbsSat.GraphPath.Model.Decision
import AbsSat.GraphPath.Model.LocalContradiction
import AbsSat.GraphPath.Model.UnitPropagation
import AbsSat.GraphPath.Model.DriverPropagation
import AbsSat.GraphPath.Model.KeyBranching
import AbsSat.GraphPath.Model.PinSupport
import AbsSat.GraphPath.Model.PartialPaths
import AbsSat.GraphPath.Model.SubsetSemantics
import AbsSat.GraphPath.Model.EmptinessReduction
import AbsSat.GraphPath.Model.PathLattice
import AbsSat.GraphPath.Model.NoDeadEnd
import AbsSat.GraphPath.Model.TopPhantom
import AbsSat.GraphPath.Model.FinalReadable
import AbsSat.GraphPath.Model.AuthorReader
import AbsSat.GraphPath.Model.ReaderPin
import AbsSat.GraphPath.Model.DescentInvariant
import AbsSat.GraphPath.Model.JoinDescent
import AbsSat.GraphPath.Model.FilterDescent
import AbsSat.GraphPath.Model.RemovalClosure
import AbsSat.GraphPath.Model.ReviewNodes
import AbsSat.GraphPath.Model.FabricInduction
import AbsSat.GraphPath.Model.ChainFabric
import AbsSat.GraphPath.Model.NoZombies
import AbsSat.GraphPath.Model.IdSeparator
import AbsSat.GraphPath.Model.ParentOwners
import AbsSat.GraphPath.Model.LitOwners
import AbsSat.GraphPath.Model.IdDiesProof
import AbsSat.GraphPath.Model.FixAgreeInv
import AbsSat.GraphPath.Model.UnitPropReview
import AbsSat.GraphPath.Model.HornDecision
import AbsSat.GraphPath.Model.IdClosureSep
import AbsSat.GraphPath.Model.IdClosureLevels
import AbsSat.GraphPath.Model.DeadClosure
import AbsSat.GraphPath.Model.SacClosure
import AbsSat.GraphPath.Model.SacFilter
import AbsSat.GraphPath.Model.ConservationCore
import AbsSat.GraphPath.Model.ConservationFilter
import AbsSat.GraphPath.Model.Oracle
import AbsSat.GraphPath.Model.CertifiedVerdict
import AbsSat.GraphPath.Model.ClauseFilter
import AbsSat.GraphPath.Model.TriReview
import AbsSat.GraphPath.Model.PrefixConservation
import AbsSat.GraphPath.Model.PrefixDecode
import AbsSat.GraphPath.Model.FabricAdd
import AbsSat.GraphMap.CnfHypergraph
import AbsSat.GraphMap.CnfReducer
import AbsSat.GraphMap.CnfSelection
import AbsSat.GraphMap.CnfMapImproves
import AbsSat.GraphPath.Model.AggressiveReview
import AbsSat.GraphPath.Model.ReaderAgg
import AbsSat.GraphPath.Model.ReaderAggRun
import AbsSat.GraphPath.Model.PinExact
import AbsSat.GraphPath.Model.AggFixpoint
import AbsSat.GraphPath.Model.PinExactBoundary
import AbsSat.GraphPath.Model.AnchoredSurvive
import AbsSat.GraphPath.Model.SliceSupport
import AbsSat.GraphPath.Model.AggInvariants
import AbsSat.GraphPath.Model.SliceExact
import AbsSat.GraphPath.Model.PinExactSome
import AbsSat.GraphPath.Model.AdjacentOwners
import AbsSat.GraphPath.Model.SpcSupport
import AbsSat.GraphPath.Model.PairChain
import AbsSat.GraphPath.Model.EmbeddedSupport
import AbsSat.GraphPath.Model.BranchRun
import AbsSat.GraphPath.Model.BranchLines
import AbsSat.GraphPath.Model.BranchCompat
import AbsSat.GraphPath.Model.BranchReader
import AbsSat.GraphPath.Model.Hereditary
import AbsSat.GraphPath.Model.HereditaryBuild
import AbsSat.GraphPath.Model.HereditaryUp
import AbsSat.GraphPath.Model.HereditaryRun
import AbsSat.GraphPath.Model.JoinProvenance
import AbsSat.GraphPath.Model.ParentWitness
import AbsSat.GraphPath.Model.RunEnv
import AbsSat.GraphPath.Model.NoDeadEndVerdict
import AbsSat.GraphPath.Model.Descent
import AbsSat.GraphPath.Model.DescentUp
import AbsSat.GraphPath.Model.DescentJoin
import AbsSat.GraphPath.Model.DescentFilter
import AbsSat.GraphPath.Model.DescentRun
import AbsSat.GraphPath.Model.Exactness
import AbsSat.GraphPath.Model.CertificateSet
import AbsSat.GraphPath.Model.SendDistrib
import AbsSat.GraphPath.Model.ReviewJoin
import AbsSat.GraphPath.Model.SupportSplit
import AbsSat.GraphPath.Model.OraclePath
import AbsSat.GraphPath.Model.LinkedChain
import AbsSat.GraphPath.Model.SliceInvariant
import AbsSat.GraphPath.Model.RoundInvariant
import AbsSat.GraphPath.Model.DeclaredVerdict
import AbsSat.GraphPath.Model.Answer
import AbsSat.GraphPath.Model.ReaderComplete
import AbsSat.GraphPath.Model.NodeLevel
import AbsSat.GraphPath.Model.SeqPin
import AbsSat.GraphPath.Model.WeakPairs
import AbsSat.GraphPath.Model.Greedy
import AbsSat.GraphPath.Model.PinExtends
import AbsSat.GraphPath.Model.ReaderDescent
import AbsSat.GraphPath.Model.ReaderTop
import AbsSat.GraphPath.Model.ReaderBT
import AbsSat.GraphPath.Model.PinSplit
import AbsSat.GraphPath.Model.PinUp
import AbsSat.GraphPath.Model.TripleA
import AbsSat.GraphPath.Model.JoinSide
import AbsSat.GraphPath.Model.PartSplitReal
import AbsSat.GraphPath.Model.UnionPaths
import AbsSat.GraphPath.Model.PairPins
import AbsSat.GraphPath.Model.ConservationPrefix
import AbsSat.GraphPath.Model.RunNoBorrow
import AbsSat.GraphPath.Model.LiveSolution
import AbsSat.GraphPath.Model.RunInhabited
import AbsSat.GraphPath.Model.RunSteps
import AbsSat.GraphPath.Model.AncestorOwned
import AbsSat.GraphPath.Model.SupportedRun
import AbsSat.GraphPath.Model.WeakNoop
import AbsSat.GraphPath.Model.ClausePins
import AbsSat.GraphPath.Model.RunHistory
import AbsSat.GraphPath.Model.ClauseReview
import AbsSat.GraphPath.Model.PinHistory
import AbsSat.GraphPath.Model.PinSend
import AbsSat.GraphPath.Model.PinVar
import AbsSat.GraphPath.Model.PinClause
import AbsSat.GraphPath.Model.PinDeath
import AbsSat.GraphPath.Model.ReaderChain
import AbsSat.GraphPath.Model.TablesSoundBuild
import AbsSat.GraphPath.Model.OwnerChainedBuild
import AbsSat.GraphPath.Model.TopGoodUp
import AbsSat.GraphPath.Model.SegReview
import AbsSat.GraphPath.Model.FullExt
import AbsSat.GraphPath.Model.ReaderLadder
import AbsSat.GraphPath.Model.LineSelf
import AbsSat.GraphPath.Model.LineExt
import AbsSat.GraphPath.Model.FullExt1
import AbsSat.GraphPath.Model.Ladder1
import AbsSat.GraphPath.Model.PinPairs
import AbsSat.GraphPath.Model.StepFilter
import AbsSat.GraphPath.Model.SendSeq
import AbsSat.GraphPath.Model.TablesExact
import AbsSat.GraphPath.Model.ExactSeq
import AbsSat.GraphPath.Model.Ladder2
import AbsSat.GraphPath.Model.PinAliveChain
import AbsSat.GraphPath.Model.ReaderExec
import AbsSat.GraphPath.Model.HereditaryValid
import AbsSat.GraphPath.Model.ImprovesCima
import AbsSat.GraphPath.Model.PureDriverImproves
import AbsSat.GraphPath.Model.ConservationImproves
import AbsSat.GraphPath.Model.ReviewWorkImproves
import AbsSat.GraphPath.Model.PureDriverPins
import AbsSat.GraphPath.Model.SeparationPins
import AbsSat.GraphPath.Model.ConservationPins
import AbsSat.SatMachine.PureSatMachineImproves
import AbsSat.SatMachine.PureProofsImproves
import AbsSat.SatMachine.FrontierReduction
import AbsSat.SatMachine.FrontierSendBounds
import AbsSat.SatMachine.ImprovesLoad
import AbsSat.Cnf.ClauseOrder
import AbsSat.Cnf.FrontierDerive
import AbsSat.Cnf.FrontierDP
