import AbsSat.Cnf.Formula
import AbsSat.Cnf.Dimacs
import AbsSat.Cnf.BruteForce
import AbsSat.Cnf.UnitProp
import AbsSat.Cnf.HornModel
import AbsSat.GraphMap.CnfMap
import AbsSat.GraphMap.CnfMapDiff
import AbsSat.GraphPath.Model.MapReachable
import AbsSat.GraphPath.Model.CnfChain
import AbsSat.GraphPath.Model.L7
import AbsSat.GraphPath.Model.Conservation
import AbsSat.GraphPath.Model.PureDriver
import AbsSat.GraphMap.CnfSel
-- lean_project/AbsSat.lean

import AbsSat.GraphPath.GraphPath
-- import AbsSat.GraphPath.GraphPathFilter -- Logic merged into GraphPath

import AbsSat.GraphPath.GraphPathVisual
import AbsSat.GraphPath.Reader.PathReader
import AbsSat.GraphPath.Reader.PathExpReader
import AbsSat.SatMachine.DiffTest
import AbsSat.Utils.ExhaustiveSolver
import AbsSat.Utils.Checker
import AbsSat.Db.Machine.Cols.ColTimeline
import AbsSat.Db.Map.Cols.MapColVars
import AbsSat.GraphMap.MapReqs
import AbsSat.GraphMap.Hypergraph
import AbsSat.GraphMap.HyperProbe
import AbsSat.Utils.Alias
import AbsSat.Db.Path.Cols.PathColNodes
import AbsSat.Db.Path.Docs.PathDocNode
import AbsSat.Db.Path.Docs.PathDocOwners

-- Pure-model formal verification (soundness + completeness of the
-- abstract 3SAT machine). Imported here so the proofs are checked as
-- part of the default build, not just on demand.
import AbsSat.SatMachine.Model.Soundness
import AbsSat.SatMachine.Model.Completeness
import AbsSat.SatMachine.PureProofs

-- Pure mirror of the Owners graph (bridge phases F1-F2: structures,
-- operations, and the review-loop fuel lemmas). Same rationale.
import AbsSat.GraphPath.Model.GPathM
import AbsSat.GraphPath.Model.Fuel
import AbsSat.GraphPath.Model.Reachable
import AbsSat.GraphPath.Model.Denot
import AbsSat.GraphPath.Model.OwnersInvariants
import AbsSat.GraphPath.Model.Filter
import AbsSat.GraphPath.Model.L6
import AbsSat.GraphPath.Model.Join
import AbsSat.GraphPath.Model.Up
import AbsSat.GraphPath.Model.L6Up
import AbsSat.GraphPath.Model.Review
import AbsSat.GraphPath.Model.CleanInvalid
import AbsSat.GraphPath.Model.Coherence
import AbsSat.GraphPath.Model.AddNode
import AbsSat.GraphPath.Model.JoinSound
import AbsSat.GraphPath.Model.ArcConsistency
import AbsSat.GraphPath.Model.ZeroOneAll
import AbsSat.GraphPath.Model.Link
import AbsSat.GraphPath.Model.WidthProbe
import AbsSat.GraphPath.Model.Validate
import AbsSat.GraphPath.Model.L6Search
import AbsSat.GraphPath.Model.Certificate
import AbsSat.GraphPath.Model.Verdict
import AbsSat.GraphPath.Model.NodeIds
import AbsSat.GraphPath.Model.Reader
import AbsSat.GraphPath.Model.Extendable
import AbsSat.GraphPath.Model.DownVerdict
import AbsSat.GraphPath.Model.PickInduction
import AbsSat.GraphPath.Model.Certifies
import AbsSat.GraphPath.Model.GownersNodes
import AbsSat.GraphPath.Model.Candidates
import AbsSat.GraphPath.Model.Parents
import AbsSat.GraphPath.Model.PathExists
import AbsSat.GraphPath.Model.Ownership
import AbsSat.GraphPath.Model.Sons
import AbsSat.GraphPath.Model.SelfOwn
import AbsSat.GraphPath.Model.MapChain
import AbsSat.GraphPath.Model.ParentId
import AbsSat.GraphPath.Model.Bridge
import AbsSat.GraphPath.Model.Pinned
import AbsSat.GraphPath.Model.Threaded
import AbsSat.GraphPath.Model.Survive
import AbsSat.GraphPath.Model.ExtendSearch
import AbsSat.GraphPath.Model.SymReview
import AbsSat.GraphMap.SymCampaign
import AbsSat.GraphPath.Model.Fabric
import AbsSat.GraphPath.Model.NodeInvariant
import AbsSat.GraphPath.Model.Decision
import AbsSat.GraphPath.Model.LocalContradiction
import AbsSat.GraphPath.Model.UnitPropagation
import AbsSat.GraphPath.Model.DriverPropagation
import AbsSat.GraphPath.Model.KeyBranching
import AbsSat.GraphPath.Model.PinSupport
import AbsSat.GraphPath.Model.PartialPaths
import AbsSat.GraphPath.Model.SubsetSemantics
import AbsSat.GraphPath.Model.EmptinessReduction
import AbsSat.GraphPath.Model.PathLattice
import AbsSat.GraphPath.Model.NoDeadEnd
import AbsSat.GraphPath.Model.TopPhantom
import AbsSat.GraphPath.Model.FinalReadable
import AbsSat.GraphPath.Model.AuthorReader
import AbsSat.GraphPath.Model.ReaderPin
import AbsSat.GraphPath.Model.DescentInvariant
import AbsSat.GraphPath.Model.JoinDescent
import AbsSat.GraphPath.Model.FilterDescent
import AbsSat.GraphPath.Model.RemovalClosure
import AbsSat.GraphPath.Model.ReviewNodes
import AbsSat.GraphPath.Model.FabricInduction
import AbsSat.GraphPath.Model.ChainFabric
import AbsSat.GraphPath.Model.NoZombies
import AbsSat.GraphPath.Model.IdSeparator
import AbsSat.GraphPath.Model.ParentOwners
import AbsSat.GraphPath.Model.LitOwners
import AbsSat.GraphPath.Model.IdDiesProof
import AbsSat.GraphPath.Model.FixAgreeInv
import AbsSat.GraphPath.Model.UnitPropReview
import AbsSat.GraphPath.Model.HornDecision
import AbsSat.GraphPath.Model.IdClosureSep
import AbsSat.GraphPath.Model.IdClosureLevels
import AbsSat.GraphPath.Model.DeadClosure
import AbsSat.GraphPath.Model.SacClosure
import AbsSat.GraphPath.Model.SacFilter
import AbsSat.GraphPath.Model.ConservationCore
import AbsSat.GraphPath.Model.ConservationFilter
import AbsSat.GraphPath.Model.Oracle
import AbsSat.GraphPath.Model.CertifiedVerdict
import AbsSat.GraphPath.Model.ClauseFilter
import AbsSat.GraphPath.Model.TriReview
import AbsSat.GraphPath.Model.SymTriReview
import AbsSat.GraphPath.Model.PrefixConservation
import AbsSat.GraphPath.Model.PrefixDecode
import AbsSat.GraphPath.Model.FabricAdd
import AbsSat.GraphMap.CnfHypergraph
import AbsSat.GraphMap.CnfReducer
import AbsSat.GraphMap.CnfSelection
import AbsSat.GraphMap.CnfMapImproves
import AbsSat.GraphPath.Model.AggressiveReview
import AbsSat.GraphPath.Model.ReaderAgg
import AbsSat.GraphPath.Model.ReaderAggRun
import AbsSat.GraphPath.Model.PinExact
import AbsSat.GraphPath.Model.PureDriverImproves
import AbsSat.GraphPath.Model.ConservationImproves
import AbsSat.GraphPath.Model.ReviewWorkImproves
import AbsSat.GraphPath.Model.PureDriverPins
import AbsSat.GraphPath.Model.SeparationPins
import AbsSat.GraphPath.Model.ConservationPins
import AbsSat.SatMachine.PureSatMachineImproves
import AbsSat.SatMachine.PureProofsImproves
import AbsSat.SatMachine.FrontierReduction
import AbsSat.SatMachine.FrontierSendBounds
import AbsSat.SatMachine.ImprovesLoad
import AbsSat.Cnf.ClauseOrder
import AbsSat.Cnf.FrontierDerive
import AbsSat.Cnf.FrontierDP
