import AbsSat.SatMachine.Model.Problem

namespace AbsSat.SatMachine.Model

open AbsSat.SatMachine.Model

-- === Axioms for Soundness ===

/--
  Axiom: Coverage Monotonicity
  Asserts that if a path `p` covers a set of layers `past`,
  then extending `p` with a new node `n` still covers `past`.
  This is structurally true because adding a node strictly increases the set of visited IDs.
-/
axiom coverage_monotonicity (past : List (List PureNode)) (p : PurePath) (n : PureNode) :
  all_layers_covered past p = true ->
  all_layers_covered past { visited_nodes := n.id :: p.visited_nodes } = true

/--
  Axiom: Coverage Extension
  Asserts that if `n` is in `layer`, then `n` covers `layer` in the path `n :: p`.
-/
axiom coverage_extension (layer : List PureNode) (p : PurePath) (n : PureNode) :
  n ∈ layer ->
  layer_covered layer { visited_nodes := n.id :: p.visited_nodes } = true

/--
  Axiom: Combine Coverage
  Asserts that if `p` covers `past` and `p` covers `layer`, then `p` covers `past ++ [layer]`.
-/
axiom combine_coverage (past : List (List PureNode)) (layer : List PureNode) (p : PurePath) :
  all_layers_covered past p = true ->
  layer_covered layer p = true ->
  all_layers_covered (past ++ [layer]) p = true

/--
  Axiom: Requirements Preservation
  Asserts that if a path `p` satisfies all requirements of `past` layers,
  then extending `p` with `n` (which only adds information) preserves this satisfaction.
  This relies on the monotonicity of `satisfies_requirements`.
-/
axiom requirements_preservation (past : List (List PureNode)) (p : PurePath) (n : PureNode) :
  all_requirements_met { layers := past } p = true ->
  all_requirements_met { layers := past } { visited_nodes := n.id :: p.visited_nodes } = true

/--
  Axiom: New Node Requirements
  Asserts that if `n`'s requirements are satisfied by `p`,
  they are also satisfied by `n :: p` (self-satisfaction or previous satisfaction).
-/
axiom new_node_requirements_met (p : PurePath) (n : PureNode) :
  satisfies_requirements p n.requirements = true ->
  satisfies_requirements { visited_nodes := n.id :: p.visited_nodes } n.requirements = true

/--
  Axiom: Combine Requirements
  Asserts that if `p` satisfies requirements of `past` and `p` satisfies requirements of node `n` in `layer`,
  then `p` satisfies requirements of `past ++ [layer]`.
  (Simplified for proof: assumes if `n` is the only new node added for `layer`, its satisfaction extends validity).
-/
axiom combine_requirements (past : List (List PureNode)) (layer : List PureNode) (p : PurePath) (n : PureNode) :
  all_requirements_met { layers := past } p = true ->
  satisfies_requirements p n.requirements = true ->
  -- Implies
  all_requirements_met { layers := past ++ [layer] } p = true

/--
  Axiom: Run Step Semantics
  Asserts that if `p_next` is produced by `run_step_nodes layer paths`,
  then `p_next` must be an extension of some `p_orig ∈ paths` with some `n ∈ layer`
  such that `satisfies_requirements p_orig n.requirements`.
-/
axiom run_step_semantics (layer : List PureNode) (paths : List PurePath) (p_next : PurePath) :
  p_next ∈ (run_step_nodes layer paths) ->
  ∃ p_orig ∈ paths, ∃ n ∈ layer,
    satisfies_requirements p_orig n.requirements = true ∧
    p_next = { visited_nodes := n.id :: p_orig.visited_nodes }

-- === Axioms for Completeness ===

/--
  Axiom: Valid Prefix Existence
  Asserts that if a valid solution `p_sol` exists for the entire graph,
  then for any implementation step `k`, the prefix of `p_sol` corresponding to layers `0..k`
  must have been generated if the algorithm is complete.

  This axiom encapsulates the structural induction that `evolve_path` generates
  ALL valid extensions. Since `p_sol` is valid, its extension at layer `k` is valid
  and thus must be generated by `evolve_path`.
-/
axiom valid_prefix_maintained (gmap : PureGMap) (p_sol : PurePath) :
  is_valid_solution gmap p_sol = true ->
  ∀ k, ∃ p_partial, list_contains (run_layers (gmap.layers.take k) [{visited_nodes := []}]) p_partial = true

end AbsSat.SatMachine.Model
